//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar_dates
    {
        public int id { get; set; }
        public string C_service_id { get; set; }
        public string date { get; set; }
        public Nullable<byte> exception_type { get; set; }
    }
}
