//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop_times
    {
        public int ID { get; set; }
        public string C_trip_id { get; set; }
        public Nullable<System.DateTime> arrival_time { get; set; }
        public Nullable<System.DateTime> departure_time { get; set; }
        public Nullable<int> stop_id { get; set; }
        public Nullable<short> stop_sequence { get; set; }
        public string stop_headsign { get; set; }
        public Nullable<byte> pickup_type { get; set; }
        public Nullable<byte> drop_off_type { get; set; }
        public Nullable<double> shape_dist_traveled { get; set; }
    }
}
